### ISSUE TITLE
Error de runtime con Net Core 2.0

### ISSUE THREAD

**Issue by christianrusso** [mercadopago/dx-dotnet#72]
Estoy intentando correr la SDK con Net Core 2.0 y me tira la excepcion siguiente:

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Web.HttpRuntime' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at MercadoPago.MPCache.RemoveFromCache(String key)
at MercadoPago.MPBase.CallAPI(HttpMethod httpMethod, String path, PayloadType payloadType, JObject payload, WebHeaderCollection colHeaders, Boolean useCache, Int32 requestTimeout, Int32 retries)
at MercadoPago.MPBase.ProcessMethod[T](Type clazz, T resource, String methodName, Dictionary`2 parameters, Boolean useCache)
at MercadoPago.MPBase.ProcessMethod[T](String methodName, Boolean useCache)
at MercadoPago.Resources.Preference.Save()
at testmp.Program.Main(String[] args) in /Users/usuario/Desktop/testmp/Program.cs:line 37

**Comment by fberasategui** [comment]
@christianrusso este SDK no soporta .NET Core.

Podes usar la [Versión Extraoficial de Lexim](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk)

**Comment by MercadoPagoDevelopers** [comment]
Hola @christianrusso,

Antes que nada te pedimos disculpas por las demoras en la devolución de tus reportes.

**Queremos contarte que lanzamos una nueva versión de la SDK que incluye la mayoría de las sugerencias realizadas** por la comunidad en este repositorio. Por lo tanto, todos los reportes existentes serán cerrados.

Estamos trabajando para estar siempre actualizados y comunicar las últimas novedades.  

Esperamos continuar recibiendo tus comentarios, problemas y aportes para seguir mejorando.

Muchas gracias.
El equipo de desarrolladores de Mercado Pago.
